#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/reservationDB?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=admin
#spring.datasource.password=admin123

# \uBE0C\uB77C\uC6B0\uC838\uC5D0\uC11C \uC2A4\uD504\uB9C1\uBD80\uD2B8\uC758 \uC624\uB958 \uD398\uC774\uC9C0\uB97C \uC548\uBCF4\uC5EC\uC8FC\uB3C4\uB85D \uC124\uC815
server.error.whitelabel.enabled=false

server.servlet.session.timeout=1800

# \uB85C\uAE45 \uC124\uC815
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

# persistence-unit \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.hbm2ddl.auto=none

# redis \uC124\uC815
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# Logging
#logging.level.org.springframework=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

